name: ci
on: [push, pull_request]
permissions:
  contents: read
jobs:
  ci:
    uses: forwardai-dev/ci-workflows/.github/workflows/full.yml@v1
    with:
      package-name: "aah"
      src-paths: "src"
      lint-paths: "src tests scripts examples"
      coverage-min: 90
      run-docs-sync: true
